FIRManagement/urls.py
from django.contrib import admin
from django.urls import path
from AdminApp.views import (
    Login,
    Logout,
    Action,
    Changepass, 
    Forgotpass,
    Forgotpassuser, 
    Fir_section, 
    Lodge_fir, 
    Regd, 
    Myprofile, 
    Police_view, 
    Track_fir, 
    Track_complain, 
    EditFir,
    DeleteFir,
    Profiledata,
    UpdateProfile,
    All_user,
    All_Police_User,
    All_Victim_User,
    All_Admin_User,
    EditUser,
    ViewUser,
    Dashboard,
    DeleteUser

)
from PublicApp.views import Contact, Gallery, Index, Services
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',Login,name='login'),
    path('logout/',Logout,name='logout'),
    path('action/',Action,name='action'),
    path('changepass/',Changepass,name='changepass'),
    path('forgotpass/',Forgotpass,name='forgotpass'),
    path('forgotpass-user/',Forgotpassuser,name='forgotpass-user'),
    path('fir-section/',Fir_section,name='fir-section'),
    
    path('myprofile/',Myprofile,name='myprofile'),
    path('police-view/',Police_view,name='police-view'),
    path('track-fir/',Track_fir,name='track-fir'),
    path('track-complain/',Track_complain,name='track-complain'),
    
    path('lodge-fir/',Lodge_fir,name='lodge-fir'),
    path('edit-fir/<int:id>/',EditFir,name='edit-fir'),
    path('delete-fir/<int:id>/', DeleteFir,name='delete-fir'),

    path('contact/',Contact,name='contact'),
    path('gallery/',Gallery,name='gallery'),
    path('',Index,name='index'),
    
    path('regd/',Regd,name='regd'),
    path('services/',Services,name='services'),
    path('profiledata/',Profiledata,name='profiledata'),
    path('updateprofile/', UpdateProfile, name='updateprofile'),
    
    path('all-user/', All_user, name='all-user'),
    path('all-police-user/', All_Police_User, name='all-police-user'),
    path('all-victim-user/', All_Victim_User, name='all-victim-user'),
    path('all-admin-user/', All_Admin_User, name='all-admin-user'),
    
    path('view-user/<int:id>/', ViewUser, name='edit-user'),
    path('edit-user/<int:id>/', EditUser, name='edit-user'),
    path('delete-user/<int:id>/', DeleteUser, name='delete-user'),

    path('dashboard/', Dashboard, name='dashboard')


] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'AdminApp.views.error_404'

AdminApp/models.py
from django.contrib.auth.models import User
from django.db import models
import random

# Create your models here.
class UserProfile(models.Model):
    USER_TYPES = [
        ('Victim', 'Victim'),
        ('Police Staff', 'Police Staff'),
        ('SP', 'SP'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='user_details')
    profilePicture = models.ImageField(blank=True, null=True)
    DOB = models.DateField()
    contact_No = models.PositiveIntegerField()
    userType = models.CharField(max_length=20, choices= USER_TYPES, default= 'Victim')
    gender = models.CharField(max_length=10)
    adhaar_no = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return self.user.username


class FIR_SECTION(models.Model):
    FIR_STATUS = [
        ('Pending', 'Pending'),
        ('Waiting for Witness', 'Waiting for Witness'),
        ('Cancelled','Cancelled'),
        ('Completed','Completed'),
    ]
    
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255)
    place_of_incident=models.CharField(max_length=255)
    category=models.CharField(max_length=255)
    description=models.TextField()
    incident_date = models.DateField(null=True, blank=True)
    incident_time = models.TimeField(null=True, blank=True)
    witness_name=models.CharField(max_length=255, null=True, blank=True)
    mobile_no=models.PositiveIntegerField(null=True, blank=True)
    status = models.CharField(max_length=20, choices= FIR_STATUS, default= 'Pending')
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class Track_FIR(models.Model):
    
    CURRENT_STATUS = [
        ('InProgress', 'InProgress'),
        ('Waiting for Witness', 'Waiting for Witness'),
        ('Cancelled','Cancelled'),
        ('Resolved','Resolved'),
        ('Forwared to Court','Forwared to Court'),
    ]
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    fir = models.ForeignKey(FIR_SECTION, on_delete=models.CASCADE, related_name='track_fir')
    current_status = models.CharField(max_length=50, choices= CURRENT_STATUS, default= 'InProgress')
    police_station=models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fir.subject


class OTP(models.Model):
    def Otp_generator():
        return random.randint(1000,1999)

    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='user_otp')
    otp = models.PositiveIntegerField(default=Otp_generator)
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'OTP for ', self.user.username

AdminApp/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .models import UserProfile, OTP, FIR_SECTION, Track_FIR
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q

import random
# Create your views here.

def Login(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('login')
    msg=""
    if request.method == "POST":
        user = request.POST["username"]
        password = request.POST["password"]
        data = authenticate(username=user, password=password)
        if data != None:
            login(request, data)
            return redirect("profiledata")
        msg='Incorrect username or password'
    return render(request, 'login.html',{'msg':msg})


def Logout(request):
    logout(request)
    return redirect("index")


def Regd(request):
    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST.get('pass1')
        pass2 = request.POST.get('pass2')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        contact = request.POST.get('contact')
        DOB = request.POST.get('DOB')
        profile_pic = request.FILES.get('profile_pic')
        Adhaar_no = request.POST.get('adhaar_no')
        gender= request.POST.get('gender')
        usertype= request.POST.get('usertype')
        
        if pass1 != pass2:
            message = 'Password should be same !'
            return render(request, 'regd.html', {'message': message})
        
        if len(contact) != 10:
            message = 'Contact should be 10 digit only.'
            return render(request, 'regd.html', {'message': message})
        try:
            u = User.objects.create_user(
                username=username, email=email, password=pass1, first_name=first_name, last_name=last_name)
        except:
            message = 'User name already exists!'
            return render(request, 'regd.html', {'message': message})
        UserProfile.objects.create(
            user=u, contact_No=contact, DOB=DOB, profilePicture=profile_pic, userType=usertype, gender=gender, adhaar_no=Adhaar_no)

        return redirect('login')

    return render(request, 'regd.html')

def Action(request):
    if not request.user.is_authenticated:
        return redirect('login')
    return render(request,'action.html')


def Changepass(request):
    if not request.user.is_authenticated:
        return redirect('login')
    message = ''
    if request.method == 'POST':
        oldpass = request.POST.get('oldpass')
        pass1 = request.POST.get('pass1')
        pass2 = request.POST.get('pass2')
        if pass1 != pass2:
            message = 'Password should be same !'
            return render(request, 'changepass.html', {'message': message})
        try:
            u = User.objects.get(username=request.user.username)
        except:
            message = 'Please enter correct User Name!'
            return render(request, 'changepass.html', {'message': message})

        check = u.check_password(oldpass)
        if check:
            u.set_password(pass1)
            u.save()
            data = authenticate(username=u.username, password=pass1)
            if data != None:
                login(request, data)
            return redirect("profiledata")
        message = 'Please enter valid Old password!'
        return render(request, 'changepass.html', {'message': message})
    return render(request,'changepass.html')


def Forgotpassuser(request):
    message = ''
    if request.method == 'POST':
        uname = request.POST.get('username')
        try:
            u = User.objects.get(username=uname)
        except:
            message = 'Username doesnot exit.'
            return render(request,'forgotpass-user.html',{'message': message})
        try:
            to_email = [u.email]
        except:
            message = 'Email is not valid.'
            return render(request,'forgotpass-user.html',{'message': message})
        
        otp= OTP.objects.create(user=u)
        subject = 'OTP FOR CRIME MANAGEMENT USER'
        body = f'Hi,{u.username} Your OTP for forgot password is {otp.otp}'
        from_email = settings.EMAIL_HOST_USER
       
        send_mail(subject,body,from_email,to_email, fail_silently=True)
        return redirect('forgotpass')
    return render(request,'forgotpass-user.html')


def Forgotpass(request):
    message = ''
    if request.method == 'POST':
        otp = request.POST.get('otp')
        uname = request.POST.get('uname')
        newpassword1 = request.POST.get('newpassword1')
        newpassword2 = request.POST.get('newpassword2')
        if newpassword1 != newpassword2:
            message = 'Password should be same !'
            return render(request, 'forgotpass.html', {'message': message})
        try:
            u = User.objects.get(username=uname)
        except:
            message = 'Please enter correct User Name!'
            return render(request, 'forgotpass.html', {'message': message})
        u_otp=OTP.objects.filter(user=u).order_by('-created_at').first()
        print(type(u_otp.otp),type(otp))
        if str(u_otp.otp) == otp:
            u.set_password(newpassword1)
            u.save()
            return redirect('login')
        message = 'Please provide valid OTP'
        return render(request, 'forgotpass.html', {'message': message})
    return render(request,'forgotpass.html')


def Fir_section(request):
    if not request.user.is_authenticated:
        return redirect('login')
    return render(request,'fir-section.html')


def Lodge_fir(request):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.method == "POST":
        category = request.POST.get('category')
        subject = request.POST.get('subject')
        description = request.POST.get('description')
        incident_date = request.POST.get('incident_date')
        incident_time = request.POST.get('incident_time')
        place_of_incident = request.POST.get('place_of_incident')
        mobile_no = request.POST.get('mobile_no')
        eye_witness_name = request.POST.get('eye_witness_name')
        police_station = request.POST.get('police_station')

        if len(mobile_no) != 10:
            msg="Please provide valid phone number"
            return render(request,'lodge-fir.html', {'msg':msg})
        
        f = FIR_SECTION.objects.create(
            user=UserProfile.objects.get(user=request.user),
            subject=subject,
            place_of_incident =  place_of_incident,
            category = category,
            description = description,
            incident_date = incident_date,
            incident_time = incident_time,
            witness_name = eye_witness_name,
            mobile_no = mobile_no
        )
        Track_FIR.objects.create(
            user=UserProfile.objects.get(user=request.user),
            fir=f,
            police_station = police_station
        )
        return redirect('track-fir')
    return render(request,'lodge-fir.html')


def Myprofile(request):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.method == 'POST':
        username = request.user.username
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        dob = request.POST.get('dob')
        contact = request.POST.get('contact')
        addhar = request.POST.get('addhar')
        pic = request.FILES.get('pic')
        
        if len(contact) != 10:
            msg = 'Phone Number should be 10 digit only.'
            return render(request,'myprofile.html', {'msg':msg})
        
        u = User.objects.get(username=username)
        user_profile = UserProfile.objects.get(user=u)
        u.first_name=first_name
        u.last_name=last_name
        u.email=email
        user_profile.contact_No=contact
        user_profile.adhaar_no=addhar
        user_profile.DOB=dob
        if pic:
            user_profile.profilePicture=pic

        u.save()
        user_profile.save()
        return redirect('profiledata')
    return render(request,'myprofile.html')


def Police_view(request):
    if not request.user.is_authenticated:
        return redirect('login')
    return render(request,'police-view.html')

def Track_fir(request):
    if not request.user.is_authenticated:
        return redirect('login')
    up = UserProfile.objects.get(user=request.user)
    if up.userType == "Police Staff":
        ta = Track_FIR.objects.exclude(Q(current_status="Resolved") | Q(current_status="Cancelled")).order_by('-id')
    elif up.userType == "SP":
        ta = Track_FIR.objects.all().order_by('-id')
    else:
        ta = Track_FIR.objects.filter(user=up).order_by('-id')
    
    
    page = request.GET.get('page', 1)

    paginator = Paginator(ta, 10)
    try:
        t = paginator.page(page)
    except PageNotAnInteger:
        t = paginator.page(1)
    except EmptyPage:
        t = paginator.page(paginator.num_pages)
    
    Dict = {
        'track': t
    }
    return render(request,'track-fir.html', Dict)

def Track_complain(request):
    if not request.user.is_authenticated:
        return redirect('login')
    return render(request,'track-complain.html')


def EditFir(request, id):
    if not request.user.is_authenticated:
        return redirect('login')
    
    track_fir = Track_FIR.objects.get(id=id)
    choices = Track_FIR.CURRENT_STATUS
    choice = []
    for c in choices:
        if c[0] != track_fir.current_status:
            choice.append(c[0])
        else:
            continue
    
    if request.method == "POST":

AdminApp/templates/action.html
{% extends 'base.html' %}
{% block content %}

        <div class="breadcrumbs">
            <div class="col-sm-4">
                <div class="page-header float-left">

                </div>
            </div>
        </div>
        <div class="content mt-3">
            <div class="animated fadeIn">
                <div class="row">

                    <form>
                        <label>
                          <p class="label-txt">NAME</p>
                          <input type="text" class="input">
                          <div class="line-box">
                            <div class="line"></div>
                          </div>
                        </label>
                        <label>
                          <p class="label-txt">FIR NUMBER</p>
                          <input type="text" class="input">
                          <div class="line-box">
                            <div class="line"></div>
                          </div>
                        </label>
                        <label>
                          <p class="label-txt">COMPLAIN DETAILS</p>
                          <input type="text" class="input">
                          <div class="line-box">
                            <div class="line"></div>
                          </div>
                        </label>
                        <label>
                            <p class="label-txt">OFFICER INCHARGE</p>
                            <input type="text" class="input">
                            <div class="line-box">
                              <div class="line"></div>
                            </div>
                          </label>
                        <button type="submit">NOTICE</button>
                    </form>



                </div>
            </div>
{% endblock %}

AdminApp/templates/base.html
<!doctype html> {% load static %}

<html lang="en">


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>FIR Management System </title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
    <link rel="stylesheet" href="{% static 'AdminStatic/vendors/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'AdminStatic/vendors/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}">
    <link rel="apple-touch-icon" href="{% static 'AdminStatic/apple-icon.png' %}">
    <link rel="shortcut icon" href="{% static 'AdminStatic/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'AdminStatic/vendors/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'AdminStatic/vendors/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'AdminStatic/vendors/themify-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'AdminStatic/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'AdminStatic/vendors/selectFX/css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'AdminStatic/vendors/jqvmap/dist/jqvmap.min.css' %}">
    <link rel="stylesheet" href="{% static 'AdminStatic/assets/css/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

</head>

<body>


    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">

            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#">FIR Management</a>
                
            </div>


            <ul class="nav navbar-nav">

                <h3 class="dropdown-btn text-white">
                    <a href="/dashboard/"><i class="menu-icon fa fa-dashboard "></i>&nbsp;&nbsp;&nbsp;Dashboard</a>
                </h3>

            </ul>
            <ul class="nav navbar-nav">
               {% if request.user.user_details.first.userType == 'Victim' %}
                <h6 class="dropdown-btn"><i class="menu-icon fa fa-user "><i class="fa fa-caret-down"></i>&nbsp;&nbsp;&nbsp;USER</i>
                    
                </h6>
                <div class="dropdown-container">
                    
                    <li>
                        <a href="/lodge-fir/">
                            <h6 class="menu-title text-white dropdown-btn">&nbsp;&nbsp;&nbsp;LODGE FIR</h6>
                        </a>

                    </li>
                    <li>
                        <a href="/track-fir/">
                            <h3 class="menu-title text-white dropdown-btn">&nbsp;&nbsp;&nbsp;TRACK FIR</h3>
                        </a>

                    </li>


                </div>
            </ul>{% endif %}
            {% if request.user.user_details.first.userType == 'Police Staff' %}
            <ul class="nav navbar-nav">
                <h6 class="dropdown-btn"><i class="menu-icon fa fa-male"><i class="fa fa-caret-down"></i>&nbsp;&nbsp;&nbsp;POLICE</i>
                    
                </h6>
                <div class="dropdown-container">
                    <li>
                        <a href="/track-fir/">
                            <h3 class="menu-title text-white dropdown-btn">&nbsp;&nbsp;&nbsp;FIR SECTION</h3>
                        </a>

                    </li>


                </div>
            </ul>{% endif %}
            {% if request.user.user_details.first.userType == 'SP' %}
            <ul class="nav navbar-nav">
                <h6 class="dropdown-btn">
                    <i class="menu-icon fa fa-user-secret">&nbsp;&nbsp;&nbsp;SP<i class="fa fa-caret-down"></i> </i>
                                       
                </h6>
                <div class="dropdown-container">
                    <li>
                        <a href="/track-fir/">
                            <h3 class="menu-title text-white dropdown-btn">&nbsp;&nbsp;&nbsp;TRACK FIR</h3>
                        </a>

                    </li>
                    
                    <li>
                        <a href="/all-user/">
                        <h6 class="menu-title text-white dropdown-btn">&nbsp;&nbsp;&nbsp;All Users</h6>
                        </a>

                    </li>


                </div>
            </ul>
            {% endif %}
            </div>

        </nav>
    </aside>




    <div id="right-panel" class="right-panel" style="background-image: url('/static/AdminStatic/images/224.jpeg'); height: 100%;

  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;">


        <header id="header" class="header">

            <div class="header-menu">



                <div class="col-sm-12">
                    <div class="user-area dropdown float-right">
                        
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Hi, {{request.user.username}} &nbsp; &nbsp;
                            {% if request.user.user_details.first.profilePicture %}
                                <img class="user-avatar rounded-circle" src="{{request.user.user_details.first.profilePicture.url}}" alt="Avatar">
                            {% else %}
                                <img class="user-avatar rounded-circle" src="{% static 'AdminStatic/images/figure/admin.png' %}" alt="User Avatar">
                            {% endif %}
                        </a>

                        <div class="user-menu dropdown-menu">
                            <a class="nav-link" href="/profiledata/"><i class="fa fa-user"></i> My Profile</a>
                            <a class="nav-link" href="/myprofile/"><i class="fa fa-user"></i> Update Profile</a>
                            <a class="nav-link" href="/changepass/"><i class="fa fa-lock"></i> Change Password</a>
                            <a class="nav-link" href="/logout/"><i class="fa fa-power-off"></i> Logout</a>
                        </div>
                    </div>
                </div>
            </div>

        </header>





    
{% block content %} {% endblock content %}

<script>
    var dropdown = document.getElementsByClassName("dropdown-btn");
    var i;

    for (i = 0; i < dropdown.length; i++) {
        dropdown[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var dropdownContent = this.nextElementSibling;
            if (dropdownContent.style.display === "block") {
                dropdownContent.style.display = "none";
            } else {
                dropdownContent.style.display = "block";
            }
        });
    }
</script>
<script src="{% static 'AdminStatic/vendors/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'AdminStatic/vendors/popper.js/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'AdminStatic/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'AdminStatic/assets/js/main.js' %}"></script>
<script src="{% static 'AdminStatic/vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'AdminStatic/vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'AdminStatic/vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'AdminStatic/vendors/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'AdminStatic/vendors/jszip/dist/jszip.min.js' %}"></script>
<script src="{% static 'AdminStatic/vendors/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'AdminStatic/vendors/pdfmake/build/vfs_fonts.js' %}"></script>
<script src="{% static 'AdminStatic/vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'AdminStatic/vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'AdminStatic/vendors/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
<script src="{% static 'AdminStatic/assets/js/init-scripts/data-table/datatables-init.js' %}"></script>


</body>

</html>

AdminApp/templates/edit-lodge-fir.html
{% extends 'base.html' %}
{% block content %}
        <form action="/edit-fir/{{details.id}}/" method="POST">
            {% csrf_token %}
            {% if msg %}
            <p style="color: red;">{{msg}}</p>
            {% endif %}

            <div class="row">
                <div class="col-md-6">
                
                <select name="category" class="form-control mt-5">
                    <option>{{details.fir.category}}</option>
                    {% if details.fir.category != "Theft" %}
                    <option>Theft</option>
                    {% endif %}
                    {% if details.fir.category != "Stolen" %}
                    <option>Stolen</option>
                    {% endif %}
                    {% if details.fir.category != "Murder" %}
                    <option>Murder</option>
                    {% endif %}
                    {% if details.fir.category != "Rape" %}
                    <option>Rape</option>
                    {% endif %}
                    {% if details.fir.category != "Missing Report" %}
                    <option>Missing Report</option>
                    {% endif %}
                    {% if details.fir.category != "Other" %}
                    <option>Other</option>
                    {% endif %}
              </select>
                </div>

                <div class="col-md-6">
                    <input type="text" class="form-control mt-5" style="width: 200px;" value="{{details.fir.subject}}" name="subject" placeholder="Enter Subject" required />
                </div>
            </div>

            <h4 class="pt-5">Describe Your Complain</h4>
            <div class="form-group pt-3">
                <textarea placeholder="Enter Description" name="description" class="form-control" id="exampleFormControlTextarea1" rows="3" style="height: 20vh;" required>{{details.fir.description}}</textarea>
            </div>
            <div class="form-group row">
                <label for="name" class="col-xs-3 col-form-label mr-2" style="margin-top: -5px;">Date of Incident</label>
                <div class="col-xs-9">
                    <input type="date" name="incident_date" value="{{details.fir.incident_date|date:'Y-m-d'}}" class="form-control" id="name" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="name" class="col-xs-3 col-form-label mr-2" style="margin-top: -5px;">Time of Incident</label>
                <div class="col-xs-9">
                    <input type="time" class="form-control" value="{{details.fir.incident_time|time:'H:i'}}" id="name" name="incident_time" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="name" class="col-xs-3 col-form-label mr-2" style="margin-top: -5px;">Place of Incident</label>
                <textarea name="place_of_incident"  placeholder="Place of Incident" class="form-control" id="exampleFormControlTextarea1" rows="3" required>{{details.fir.place_of_incident}}</textarea>
            </div>

            <div class="form-group row">
                <label for="name" class="col-xs-3 col-form-label mr-2" style="margin-top: -5px;">Contact Person Number</label>
                <div class="col-xs-9">
                    <input type="number" value="{{details.fir.mobile_no}}" placeholder="Contact Number" class="form-control" id="name" name="mobile_no" required />
                </div>
            </div>


            <div class="form-group row">
                <label for="name" class="col-xs-3 col-form-label mr-2" style="margin-top: -5px;">Nearest Police Station</label>
                <div class="col-xs-9">
                    <input type="text" value="{{details.police_station}}" placeholder="Near police Station" class="form-control" id="name" name="police_station" required />
                </div>
            </div>

            <div class="form-group row">
                <label for="name" class="col-xs-3 col-form-label mr-2" style="margin-top: -9px;">Any Witness</label>
                <div class="col-xs-9">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" value="{{details.fir.witness_name}}" type="text" name="eye_witness_name" id="inlineRadio1" placeholder="Enter Witness Name">                        
                    </div>
                    
                </div>
            </div>
            {% if request.user.user_details.first.userType != 'Victim' %}
            <div class="form-group row">
                <label for="name" class="col-xs-3 col-form-label mr-2" style="margin-top: -9px;">Update Status </label>
                <div class="col-xs-9">
                    <select name="status">
                        <option>{{details.get_current_status_display}}</option>
                        {% for c in choice %}
                        <option>{{c}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            {% endif %}
            <div class="form-group row">

                <div class="offset-xs-3 col-xs-9">
                    <input type="submit" class="btn btn-primary" value="Submit">
                </div>

            </div>

        </form>
    </div>
{% endblock %}